# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip && pip install python-decouple

# Copy the requirements file into the container at /app/
COPY requirements.txt /app/

# Install project dependencies
RUN pip install -r requirements.txt


# Copy the current directory contents into the container at /app/
COPY . /app/

# Expose port 8000 (not necessary for local development)
# EXPOSE 8000

# Add this line after copying your application code
RUN python manage.py collectstatic --noinput

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# Run the Kafka consumer (modify the path as needed)
CMD ["python", "consumer.py"]
